/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_parkir1;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Luxtrada R
 */
public class form1 extends javax.swing.JFrame {
    ResultSet rs;
    Statement stm;
    koneksi koneksi;
    
    /**
     * Creates new form form1
     */
    public form1() {
        initComponents();
        koneksi=new koneksi();
//        merk();
//        jurusan();
        kelas();
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height /2;
        this.setLocation(x,y);
    }
//  
    
    public void kelas(){
        try{
            stm=koneksi.con.createStatement();
            String query = "SELECT * FROM kelas";
            rs=stm.executeQuery(query);
            while(rs.next()){
                jKelas.addItem(rs.getString("kelas"));
            }rs.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"ERROR DIKelas");
        }
    }
    
    public void input_data(){
        try{
            
            stm=koneksi.con.createStatement();
//            String merk="";
//            String jurusan="";
            String kelas="";
            
//            String queryMerk="SELECT IDmerk FROM merk WHERE mrk='"+jMerk.getText()+"'";
//            String queryJurusan="SELECT IDjurusan FROM jurusan WHERE jurusan='"+jKelas1.getSelectedItem()+"'";
            String query="SELECT IDkelas FROM kelas WHERE kelas='"+jKelas.getSelectedItem()+"'";

//            rs=stm.executeQuery(queryMerk);
//            rs=stm.executeQuery(queryJurusan);
            rs=stm.executeQuery(query);
//            if(rs.next()){
//                merk=rs.getString("IDmerk");
//            }
//            if(rs.next()){
//                jurusan=rs.getString("IDjurusan");
//            }
            if(rs.next()){
                kelas=rs.getString("IDkelas");
            }
            
            String sql = "INSERT INTO kendaraan values('"+jNopol.getText()+"','"
                    +jMerk.getText()+"','"
                    +jNamken.getText()+"','"
                    +jWarna.getText()+"','"
                    +jNis.getText()+"','"
                    +jJurusan.getText()+"','"
                    +kelas+"')";
            stm.execute(sql);
            JOptionPane.showMessageDialog(null,"Data berhasil ditambahkan");
                            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Input Data ERROR");
        }
    }
    
    public void reset_form(){
        jNopol.setText("");
        jMerk.setText("");
        jNamken.setText("");
        jWarna.setText("");
        jNis.setText("");
        jJurusan.setText("");
        jKelas.setSelectedItem("- pilih -");
    }
    
    public void filternis(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Masukkan Angka","Informasi",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void filterhurufbesar(KeyEvent b){
        if(Character.isLowerCase(b.getKeyChar())){
            b.consume();
            JOptionPane.showMessageDialog(null,"Hanya angka dan huruf besar","Infomasi",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jClose = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnUlangi = new javax.swing.JButton();
        jKelas = new javax.swing.JComboBox<>();
        jMerk = new javax.swing.JTextField();
        jJurusan = new javax.swing.JTextField();
        jNopol = new javax.swing.JTextField();
        jNis = new javax.swing.JTextField();
        jWarna = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jNamken = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Tambah Data Kendaraan Siswa");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 40, 340, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("* masukkan Id jurusan pada tabel jurusan ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(130, 330, 240, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("* masukkan Id merk pada tabel merk ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(130, 160, 210, 20);

        jClose.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luxtrada R\\Documents\\NetBeansProjects\\project_parkir1\\src\\project_parkir1\\images\\close.png")); // NOI18N
        jClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCloseMouseExited(evt);
            }
        });
        jPanel1.add(jClose);
        jClose.setBounds(330, 0, 70, 40);

        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        jPanel1.add(btnSimpan);
        btnSimpan.setBounds(130, 400, 73, 23);

        btnUlangi.setText("Ulangi");
        btnUlangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlangiActionPerformed(evt);
            }
        });
        jPanel1.add(btnUlangi);
        btnUlangi.setBounds(230, 400, 73, 23);

        jKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-" }));
        jKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKelasActionPerformed(evt);
            }
        });
        jPanel1.add(jKelas);
        jKelas.setBounds(130, 350, 150, 30);
        jPanel1.add(jMerk);
        jMerk.setBounds(130, 130, 200, 30);

        jJurusan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jJurusanKeyTyped(evt);
            }
        });
        jPanel1.add(jJurusan);
        jJurusan.setBounds(130, 300, 200, 30);

        jNopol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNopolKeyTyped(evt);
            }
        });
        jPanel1.add(jNopol);
        jNopol.setBounds(130, 90, 200, 30);

        jNis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNisKeyTyped(evt);
            }
        });
        jPanel1.add(jNis);
        jNis.setBounds(130, 260, 200, 30);

        jWarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWarnaActionPerformed(evt);
            }
        });
        jPanel1.add(jWarna);
        jWarna.setBounds(130, 220, 200, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("NO Polisi");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 90, 50, 20);

        jNamken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamkenActionPerformed(evt);
            }
        });
        jPanel1.add(jNamken);
        jNamken.setBounds(130, 180, 200, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Merk");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 140, 30, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("nama kendaraan");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 190, 100, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Warna");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 230, 40, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("NIS");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 270, 20, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Jurusan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 310, 50, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Kelas");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 350, 34, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luxtrada R\\Documents\\NetBeansProjects\\project_parkir1\\src\\project_parkir1\\images\\back.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, 0, 380, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNamkenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamkenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamkenActionPerformed

    private void jWarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWarnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jWarnaActionPerformed

    private void btnUlangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlangiActionPerformed
        reset_form();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUlangiActionPerformed

    private void jCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseClicked
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jCloseMouseClicked

    private void jCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("Images/close1.png"));
        jClose.setIcon(A);
    // TODO add your handling code here:
    }//GEN-LAST:event_jCloseMouseEntered

    private void jCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseExited
        ImageIcon B = new ImageIcon(getClass().getResource("Images/close.png"));
        jClose.setIcon(B);
// TODO add your handling code here:
    }//GEN-LAST:event_jCloseMouseExited

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        if(jNopol.getText().equals("")){
            JOptionPane.showMessageDialog(null,"NO Polisi harus diisi!","Informasi",JOptionPane.ERROR_MESSAGE);
        }else if(jMerk.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Merk harus diisi!","Informasi",JOptionPane.ERROR_MESSAGE);
        }else if(jNamken.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nama Kendaraan harus diisi!","Informasi",JOptionPane.ERROR_MESSAGE);
        }else if(jWarna.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Warna harus diisi!","Informasi",JOptionPane.ERROR_MESSAGE);
        }else if(jNis.getText().equals("")){
            JOptionPane.showMessageDialog(null,"NIS harus diisi!","Informasi",JOptionPane.ERROR_MESSAGE);
        }else if(jJurusan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Jurusan harus diisi!","Informasi",JOptionPane.ERROR_MESSAGE);
        }else{
            int opsi = JOptionPane.showConfirmDialog(null,"simpan data?","Konfirmasi",JOptionPane.YES_NO_OPTION);
            if(opsi==JOptionPane.YES_OPTION){
                input_data();
                reset_form();
            }else{
                JOptionPane.showConfirmDialog(null,"Data gagal disimpan","Informasi",JOptionPane.ERROR_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void jNisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNisKeyTyped
        filternis(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jNisKeyTyped

    private void jKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKelasActionPerformed

    private void jNopolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNopolKeyTyped
        filterhurufbesar(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jNopolKeyTyped

    private void jJurusanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jJurusanKeyTyped
        filterhurufbesar(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jJurusanKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUlangi;
    private javax.swing.JLabel jClose;
    private javax.swing.JTextField jJurusan;
    private javax.swing.JComboBox<String> jKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMerk;
    private javax.swing.JTextField jNamken;
    private javax.swing.JTextField jNis;
    private javax.swing.JTextField jNopol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jWarna;
    // End of variables declaration//GEN-END:variables
}
