/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_parkir1;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Luxtrada R
 */
public class form extends javax.swing.JFrame {
    public static Connection con;
    public static ResultSet rs;
    public static Statement stm;
    /**
     * Creates new form form
     */
    public form() {
//        koneksi = new koneksi();
        initComponents();
        koneksi();
//        input_data();

        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;     
        this.setLocation(x, y);  
        
    }
    
    public void koneksi(){
        try{
            String url ="jdbc:mysql://localhost/parking";
            String user="root";
            String pass="";
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(url,user,pass);
            stm = (Statement)con.createStatement();
        }catch(Exception e){
            System.out.println("koneksi gagal"+e.getMessage());
        }
    }
    public void input_data(){
//        String formattgl="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
        String tgl_lhr = fm.format(jTanggal_lahir.getDate());
        try{
            String jk="";
            if(jLaki.isSelected()){
                jk=jLaki.getText();
            }else{
                jk=jPrempuan.getText();
            }
            stm=con.createStatement();    
            String sql="insert into siswa values('"+jNis.getText()+"','"
                    +jNama.getText()+"','"
                    +jk+"','"
                    +tgl_lhr+"','"
                    +jAlamat.getText()+"','"
                    +jNope.getText()+"')";
            stm.execute(sql);
            JOptionPane.showMessageDialog(null,"Data Berhasil Dimasukkan");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "error di input data"+e);
        }
    }
    
    public void reset_form(){
        jNis.setText("");
        jNama.setText("");
        jLaki.setSelected(false);
        jPrempuan.setSelected(false);
        jTanggal_lahir.setDate(null);
        jAlamat.setText("");
        jNope.setText("");
//        btngJK.clearSelection();
    }
    
    public void filternis(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Masukkan Angka","Informasi",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void filternope(KeyEvent b){
        if(Character.isAlphabetic(b.getKeyChar())){
            b.consume();
            JOptionPane.showMessageDialog(null,"Masukkan Angka","Informasi",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngJK = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jNama = new javax.swing.JTextField();
        jNis = new javax.swing.JTextField();
        jLaki = new javax.swing.JRadioButton();
        jPrempuan = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jTanggal_lahir = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAlamat = new javax.swing.JTextArea();
        jNope = new javax.swing.JTextField();
        jClose = new javax.swing.JLabel();
        simpan = new javax.swing.JLabel();
        form = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Tambah data siswa");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(110, 20, 200, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Jenis kelamin");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 160, 90, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Alamat");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 230, 50, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Nis");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 80, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Nama");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 120, 50, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("No Hp");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 310, 50, 20);
        jPanel1.add(jNama);
        jNama.setBounds(180, 120, 200, 30);

        jNis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNisActionPerformed(evt);
            }
        });
        jNis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNisKeyTyped(evt);
            }
        });
        jPanel1.add(jNis);
        jNis.setBounds(180, 80, 200, 30);

        btngJK.add(jLaki);
        jLaki.setForeground(new java.awt.Color(255, 255, 255));
        jLaki.setText("L");
        jLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLakiActionPerformed(evt);
            }
        });
        jPanel1.add(jLaki);
        jLaki.setBounds(180, 160, 93, 23);

        btngJK.add(jPrempuan);
        jPrempuan.setForeground(new java.awt.Color(255, 255, 255));
        jPrempuan.setText("P");
        jPrempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrempuanActionPerformed(evt);
            }
        });
        jPanel1.add(jPrempuan);
        jPrempuan.setBounds(290, 160, 90, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Tangal Lahir");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 200, 90, 20);
        jPanel1.add(jTanggal_lahir);
        jTanggal_lahir.setBounds(180, 190, 200, 30);

        jAlamat.setColumns(20);
        jAlamat.setRows(5);
        jScrollPane1.setViewportView(jAlamat);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(180, 230, 200, 70);

        jNope.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNopeKeyTyped(evt);
            }
        });
        jPanel1.add(jNope);
        jNope.setBounds(180, 310, 200, 30);

        jClose.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luxtrada R\\Documents\\NetBeansProjects\\project_parkir1\\src\\project_parkir1\\images\\close.png")); // NOI18N
        jClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCloseMouseExited(evt);
            }
        });
        jPanel1.add(jClose);
        jClose.setBounds(370, 0, 60, 31);

        simpan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luxtrada R\\Documents\\NetBeansProjects\\project_parkir1\\src\\project_parkir1\\images\\simpan.png")); // NOI18N
        simpan.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                simpanAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                simpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                simpanMouseExited(evt);
            }
        });
        jPanel1.add(simpan);
        simpan.setBounds(170, 350, 80, 30);

        form.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luxtrada R\\Documents\\NetBeansProjects\\project_parkir1\\src\\project_parkir1\\images\\back.png")); // NOI18N
        jPanel1.add(form);
        form.setBounds(0, 0, 430, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPrempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPrempuanActionPerformed

    private void jCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseClicked
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jCloseMouseClicked

    private void jCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("images/close1.png"));
        jClose.setIcon(A);
// TODO add your handling code here:
    }//GEN-LAST:event_jCloseMouseEntered

    private void jCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseExited
        ImageIcon B = new ImageIcon(getClass().getResource("images/close.png"));
        jClose.setIcon(B);
// TODO add your handling code here:
    }//GEN-LAST:event_jCloseMouseExited

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
        String tgl_lhr= fm.format(jTanggal_lahir.getDate());
        if(jNis.getText().equals("")){
            JOptionPane.showMessageDialog(null,"NIS harus diisi!","informasi",JOptionPane.ERROR_MESSAGE);
        }else if(btngJK.isSelected(null)){
            JOptionPane.showMessageDialog(null,"Jenis kelamin harus Diiisi!","Informasi",JOptionPane.ERROR_MESSAGE);
        }
        else if(jNama.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nama harus diisi!","informasi",JOptionPane.ERROR_MESSAGE);
        }else if(jAlamat.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Alamat harus diisi!","informasi",JOptionPane.ERROR_MESSAGE);
        }else if(jNope.getText().equals("")){
            JOptionPane.showMessageDialog(null,"No Telphone harus diisi!","informasi",JOptionPane.ERROR_MESSAGE);
        }else{
            int opsi = JOptionPane.showConfirmDialog(null,"Simpan Data ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
            if(opsi==JOptionPane.YES_OPTION){
                input_data();
                reset_form();
            }else{
                JOptionPane.showConfirmDialog(null, "Data tidak tersimpan","informasi",JOptionPane.ERROR_MESSAGE);
            }
        }
        
        form1 form1 = new form1();
        form1.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_simpanMouseClicked

    private void simpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseEntered
         ImageIcon A = new ImageIcon(getClass().getResource("images/simpan1.png"));
        simpan.setIcon(A);
// TODO add your handling code here:
    }//GEN-LAST:event_simpanMouseEntered

    private void simpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseExited
         ImageIcon B = new ImageIcon(getClass().getResource("images/simpan.png"));
        simpan.setIcon(B);
// TODO add your handling code here:
    }//GEN-LAST:event_simpanMouseExited

    private void simpanAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_simpanAncestorAdded

        // TODO add your handling code here:
    }//GEN-LAST:event_simpanAncestorAdded

    private void jNisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNisActionPerformed

    private void jLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLakiActionPerformed

    private void jNisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNisKeyTyped
        filternis(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jNisKeyTyped

    private void jNopeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNopeKeyTyped
        filternope(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jNopeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngJK;
    private javax.swing.JLabel form;
    private javax.swing.JTextArea jAlamat;
    private javax.swing.JLabel jClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jLaki;
    private javax.swing.JTextField jNama;
    private javax.swing.JTextField jNis;
    private javax.swing.JTextField jNope;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jPrempuan;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jTanggal_lahir;
    private javax.swing.JLabel simpan;
    // End of variables declaration//GEN-END:variables
}
