/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_parkir1;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Luxtrada R
 */
public class input extends javax.swing.JFrame {
    Statement stm;
    ResultSet rs;
    koneksi koneksi;
//    int xmouse;
//    int ymouse;
    /**
     * Creates new form input
     */
    public input() {
        initComponents();
        koneksi=new koneksi();
        IDotomatis();
//        this.setLocationRelativeTo(null);
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
    }
    
    private void IDotomatis(){
        try{
            stm=koneksi.con.createStatement();
            String sql = "SELECT * FROM admin order by id desc";
            rs=stm.executeQuery(sql);
            if(rs.next()){
                String ID = rs.getString("id").substring(5);
                String NO =""+(Integer.parseInt(ID)+1);
                String No1="";
                
                if(NO.length()==1){
                    No1="00";
                }else if(NO.length()==2){
                    No1="0";
                }else if(NO.length()==3){
                    No1="";
                }
                jId.setText("ADMIN" + No1 + NO);
            }else{
                jId.setText("ADMIN001");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Id otomatis error"+e);
        }
    }
    
    public void tambah_data(){
        try{
            stm=koneksi.con.createStatement();
            String sql="INSERT INTO admin values('"+jId.getText()+
                    "','"+jNama.getText()
                    +"','"+jEmail.getText()
                    +"','"+jPassword.getText()
                    +"','"+jNope.getText()
                    +"')";
            stm.execute(sql);
            JOptionPane.showMessageDialog(null,"Data Berhasil dimasukkan");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Tambah data ERROR!!"+e);
        }
        
    }
    
    public void reset_form(){
        jId.setText("");
        jNama.setText("");
        jEmail.setText("");
        jPassword.setText("");
        jNope.setText("");
    }
    
    public void filternope(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Masukkan angka","Informasi",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jPassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jNope = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("Images/logo.png")).getImage()
        );
        setUndecorated(true);

        jPanel2.setLayout(null);

        close.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luxtrada R\\Documents\\NetBeansProjects\\project_parkir1\\src\\project_parkir1\\images\\close.png")); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel2.add(close);
        close.setBounds(240, 0, 70, 40);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset);
        btnReset.setBounds(50, 260, 73, 23);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan);
        btnSimpan.setBounds(150, 260, 90, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Daftar Admin");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(70, 20, 130, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 150, 50, 17);

        jEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailActionPerformed(evt);
            }
        });
        jPanel2.add(jEmail);
        jEmail.setBounds(130, 140, 130, 30);

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(jPassword);
        jPassword.setBounds(130, 180, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 180, 70, 20);

        jNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaActionPerformed(evt);
            }
        });
        jPanel2.add(jNama);
        jNama.setBounds(130, 100, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 110, 50, 17);

        jNope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNopeActionPerformed(evt);
            }
        });
        jNope.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNopeKeyTyped(evt);
            }
        });
        jPanel2.add(jNope);
        jNope.setBounds(130, 220, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No HP");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 220, 50, 17);

        jId.setEditable(false);
        jPanel2.add(jId);
        jId.setBounds(130, 60, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 70, 24, 14);

        admin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luxtrada R\\Documents\\NetBeansProjects\\project_parkir1\\src\\project_parkir1\\images\\back.png")); // NOI18N
        admin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                adminMouseDragged(evt);
            }
        });
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminMousePressed(evt);
            }
        });
        jPanel2.add(admin);
        admin.setBounds(0, 2, 300, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset_form();
// TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if(jId.getText().equals("")){
            JOptionPane.showMessageDialog(null,"ID harus diisi","Informasi",JOptionPane.ERROR_MESSAGE);
        }else if(jNama.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nama harus diisi","Informasi",JOptionPane.ERROR_MESSAGE);
        }else if(jEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Email harus diisi","Informasi",JOptionPane.ERROR_MESSAGE);
        }else if(jPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Password harus diisi","Informasi",JOptionPane.ERROR_MESSAGE);
        }else if(jNope.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nomor HP harus diisi","Informasi",JOptionPane.ERROR_MESSAGE);
        }else{
            int opsi = JOptionPane.showConfirmDialog(null,"Simpan data?","KOnfirmasi",JOptionPane.YES_NO_OPTION);
            if(opsi == JOptionPane.YES_OPTION){
                tambah_data();
                reset_form();
                IDotomatis();
            }else{
                JOptionPane.showMessageDialog(null,"Data tidak tersimpan","Informasi",JOptionPane.ERROR_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jNopeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNopeActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jNopeActionPerformed

    private void jNopeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNopeKeyTyped
        filternope(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jNopeKeyTyped

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("Images/close1.png"));
        close.setIcon(A);
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon B = new ImageIcon(getClass().getResource("Images/close.png"));
        close.setIcon(B);
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseExited

    private void adminMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseDragged
//       int x = evt.getXOnScreen();
//       int y = evt.getXOnScreen();
//       
//       this.setLocation(x - xmouse, y - ymouse);
//        System.out.println(x+","+y);
// TODO add your handling cod+e here:
    }//GEN-LAST:event_adminMouseDragged

    private void adminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMousePressed
//         xmouse = evt.getX();
//        ymouse = evt.getY();
// TODO add your handling code here:
    }//GEN-LAST:event_adminMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel close;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNama;
    private javax.swing.JTextField jNope;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPassword;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
