/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_parkir1;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luxtrada R
 */
public class merk extends javax.swing.JFrame {
    public static Connection con;
    public static Statement stm;
    public static ResultSet rs;
    
    public merk() {
        initComponents();
        koneksimysql();
        Data();
        IDotomatis();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;     
        this.setLocation(x, y);
    }

    public void koneksimysql(){
        try{
            String url ="jdbc:mysql://localhost/parking";
            String user="root";
            String pass="";
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(url,user,pass);
            stm=(Statement)con.createStatement();
//            JOptionPane.showMessageDialog(null,"Berhasil koneksi");
        }catch(Exception e){
            System.out.println("Koneksi gagal"+e.getMessage());
        }
    }
    
    public void Data(){
        Object header[]={"ID Merk","Merk"};
        DefaultTableModel M = new DefaultTableModel(null,header);
        jmerk.setModel(M);
        String sql="select * from merk;";
        try{
            stm=con.createStatement();
            rs=stm.executeQuery(sql);
            while(rs.next()){
                String k1 = rs.getString(1);
                String k2 = rs.getString(2);
                String k[]={k1,k2};
                M.addRow(k);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void IDotomatis(){
        try{
            stm=con.createStatement();
            String sql = "select * from merk order by IDmerk desc";
            rs=stm.executeQuery(sql);
            if(rs.next()){
                String ID = rs.getString("IDmerk").substring(6);
                String NO = ""+(Integer.parseInt(ID)+1);
                String No1="";
                if(NO.length()==1){
                    No1="00";
                }else if(NO.length()==2){
                    No1="0";
                }
                jId.setText("IDmerk"+No1+NO);
            }else{
                jId.setText("IDmerk001");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void Tambah_Data(){
        try{
            stm=con.createStatement();
            String sql = "insert into merk values('"+jId.getText()+"','"+Merk.getText()+"')";
            stm.execute(sql);
            JOptionPane.showMessageDialog(null,"Data berhasil Dimasukkan");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void hapus(){
        try{
            stm=con.createStatement();
            String sql = "delete from merk where IDmerk='"+jId.getText()+"'";
            stm.execute(sql);
            JOptionPane.showMessageDialog(null,"Data berhasil dihapus");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void edit(){
        try{
            stm=con.createStatement();
            String sql="update merk set merk='"+Merk.getText()+"'where IDmerk='"+jId.getText()+"'";
            stm.execute(sql);
            JOptionPane.showMessageDialog(null,"Data berhasil di edit");
            Data();
            reset_form();
            btnSimpan.setEnabled(true);
        }catch(SQLException e ){
            JOptionPane.showMessageDialog(null,"Data Disimpan\n"+e);
        }
    }
    
    private void reset_form(){
        Data();
        IDotomatis();
        jId.setText("");
        Merk.setText("");
    }
    
    public void filterhurufbesar(KeyEvent a){
        if(Character.isLowerCase(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Masukkan Hanya huruf Besar","Informasi",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Merk = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jmerk = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        close.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luxtrada R\\Documents\\NetBeansProjects\\project_parkir1\\src\\project_parkir1\\images\\close1.png")); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(670, 0, 60, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tambah Data");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 80, 120, 17);

        jId.setEditable(false);
        jPanel1.add(jId);
        jId.setBounds(110, 110, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Merk");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 170, 34, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID merk");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 110, 70, 17);

        Merk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MerkActionPerformed(evt);
            }
        });
        Merk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MerkKeyTyped(evt);
            }
        });
        jPanel1.add(Merk);
        Merk.setBounds(110, 160, 150, 30);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan);
        btnSimpan.setBounds(150, 200, 90, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Merk");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 20, 110, 30);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus);
        btnHapus.setBounds(10, 240, 90, 23);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);
        btnEdit.setBounds(110, 240, 51, 23);

        jmerk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jmerk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmerkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jmerk);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(280, 70, 440, 350);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luxtrada R\\Documents\\NetBeansProjects\\project_parkir1\\src\\project_parkir1\\images\\bgDaata.png")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 74, 260, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luxtrada R\\Documents\\NetBeansProjects\\project_parkir1\\src\\project_parkir1\\images\\bg.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int opsi = JOptionPane.showConfirmDialog(null,"Hapus Data ini?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(opsi==0){
            hapus();
            reset_form();
            Data();
            btnSimpan.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null,"pilih data yang akan dihapus");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int opsi = JOptionPane.showConfirmDialog(null,"Edit data ini?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(opsi == 0){
            edit();
            Data();
            btnSimpan.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null,"pilih data yang akan di edit");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
       if(jId.getText().equals("")){
           JOptionPane.showMessageDialog(null,"ID Merk harus diisi","Konfirmasi",JOptionPane.ERROR_MESSAGE);
       }else if(Merk.getText().equals("")){
           JOptionPane.showMessageDialog(null," Merk harus diisi","Konfirmasi",JOptionPane.ERROR_MESSAGE);
       }else{
           int opsi = JOptionPane.showConfirmDialog(null,"Simpan data?","Konfirmasi",JOptionPane.YES_NO_OPTION);
          if(opsi==JOptionPane.YES_OPTION){
               Tambah_Data();
               reset_form();
               Data();
               IDotomatis();
           }else{
              JOptionPane.showConfirmDialog(null,"Data tidak tersimpan","Konfirmasi",JOptionPane.ERROR_MESSAGE);
          }
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jmerkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmerkMouseClicked
       int bar = jmerk.getSelectedRow();
       String a = jmerk.getValueAt(bar, 0).toString();
       String b = jmerk.getValueAt(bar, 1).toString();
       jId.setText(a);
       Merk.setText(b);
       btnSimpan.setEnabled(false);
       btnHapus.setEnabled(true);
       btnEdit.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmerkMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
       this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon A = new ImageIcon (getClass().getResource("Images/close.png"));
        close.setIcon(A);
// TODO add your handling code here:
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon B = new ImageIcon (getClass().getResource("Images/close1.png"));
        close.setIcon(B);
// TODO add your handling code here:
    }//GEN-LAST:event_closeMouseExited

    private void MerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MerkActionPerformed

    private void MerkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MerkKeyTyped
        filterhurufbesar(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_MerkKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(merk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(merk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(merk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(merk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new merk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Merk;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel close;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jmerk;
    // End of variables declaration//GEN-END:variables
}
