/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_parkir1;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luxtrada R
 */
public class petugas extends javax.swing.JFrame {
    ResultSet rs;
    Statement stm;
    koneksi koneksi;
    
    /**
     * Creates new form 
     */
    public petugas() {
        initComponents();
        koneksi=new koneksi();
        tampildata();
        IDotomatis();
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().width / 2;
        this.setLocation(x, y);
    }

    public void tampildata(){
        Object header[]={"ID petugas","Nama"};
        DefaultTableModel petugas = new DefaultTableModel(null,header);
        tblPetugas.setModel(petugas);
        String sql = "select * from petugas";
        try{
            stm =koneksi.con.createStatement();
            rs=stm.executeQuery(sql);
            while(rs.next()){
                String k1 = rs.getString(1);
                String k2 = rs.getString(2);
                String k[]={k1,k2};
                petugas.addRow(k);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void IDotomatis(){
        try{
            stm=koneksi.con.createStatement();
            String sql = "select * from petugas order by IDpetugas desc";
            rs=stm.executeQuery(sql);
            if(rs.next()){
                String ID = rs.getString("IDpetugas").substring(4);
                String NO = ""+(Integer.parseInt(ID)+1);
                String No1="";
                
                if(NO.length()==1){
                    No1="00";
                }else if(NO.length()==2){
                    No1="0";
                }else if(NO.length()==3){
                    No1="";
                }
                jId.setText("PETU"+ No1 + NO);
            }else{
                jId.setText("PETU001");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"ID otomatis Error","WARNING",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void input(){
        try{
            stm=koneksi.con.createStatement();
            String sql = "Insert into petugas values('"+jId.getText()+"','"+jNama.getText()+"')";
            stm.execute(sql);
            JOptionPane.showMessageDialog(null,"Data Berhasil dimasukkan");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data gagal diinputkan","WARNING",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void hapus(){
        try{
            stm=koneksi.con.createStatement();
            String sql ="delete from petugas where IDpetugas='"+jId.getText()+"'";
            stm.execute(sql);
            JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data gagal Dihapus","WARNING",JOptionPane.ERROR_MESSAGE);

        }
    }
    
    private void edit(){
        try{
            stm=koneksi.con.createStatement();
            String sql ="update petugas set nama_petugas='"+jNama.getText()+"'where IDpetugas='"+jId.getText()+"'";
            stm.execute(sql);
            JOptionPane.showMessageDialog(null,"Data berhasil di edit");
            tampildata();
            reset_form();
            btnSimpan.setEnabled(true);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data gagal Di Edit","WARNING",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void reset_form(){
        tampildata();
        IDotomatis();
        jNama.setText("");
        btnSimpan.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        close = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jNama = new javax.swing.JTextField();
        jId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPetugas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);
        btnEdit.setBounds(50, 220, 80, 23);

        btnHapus.setText("hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus);
        btnHapus.setBounds(141, 220, 70, 23);

        close.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luxtrada R\\Documents\\NetBeansProjects\\project_parkir1\\src\\project_parkir1\\images\\close.png")); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(370, 10, 60, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Data Petugas");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 40, 140, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Nama");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 130, 50, 30);

        jNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaActionPerformed(evt);
            }
        });
        jPanel1.add(jNama);
        jNama.setBounds(90, 140, 120, 30);

        jId.setEditable(false);
        jId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIdActionPerformed(evt);
            }
        });
        jPanel1.add(jId);
        jId.setBounds(90, 100, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("ID petugas");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 94, 60, 30);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan);
        btnSimpan.setBounds(50, 190, 80, 23);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset);
        btnReset.setBounds(150, 190, 61, 23);

        tblPetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPetugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPetugas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 80, 210, 340);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luxtrada R\\Documents\\NetBeansProjects\\project_parkir1\\src\\project_parkir1\\images\\back.png")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 84, 210, 160);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luxtrada R\\Documents\\NetBeansProjects\\project_parkir1\\src\\project_parkir1\\images\\bg.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 440, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIdActionPerformed

    private void jNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
         if(jId.getText().equals("")){
            JOptionPane.showMessageDialog(null,"ID Petugas harus diisi","informasi",JOptionPane.ERROR_MESSAGE);
        }else if(jNama.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Kelas harus diisi","informasi",JOptionPane.ERROR_MESSAGE);
        }else{
            int opsi = JOptionPane.showConfirmDialog(null,"simpan data?","Komfirmasi",JOptionPane.YES_NO_OPTION);
            if(opsi == JOptionPane.YES_OPTION){
                input();
                reset_form();
                tampildata();
                IDotomatis();
            }else{
                JOptionPane.showMessageDialog(null,"Data tidak tersimpan","Informasi",JOptionPane.ERROR_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("Images/close1.png"));
        close.setIcon(A);
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon B = new ImageIcon(getClass().getResource("Images/close.png"));
        close.setIcon(B);
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseExited

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int opsi=JOptionPane.showConfirmDialog(null,"Edit data ini?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(opsi==0){
            edit();
            tampildata();
            btnSimpan.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null,"pilih data yang akan di edit");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset_form();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int opsi = JOptionPane.showConfirmDialog(null,"Hapus Data ini?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(opsi == 0){
            hapus();
            reset_form();
            tampildata();
            btnSimpan.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null,"Pilih data yang akan dihapus");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPetugasMouseClicked
        int bar = tblPetugas.getSelectedRow();
        String a = tblPetugas.getValueAt(bar, 0).toString ();
        String b = tblPetugas.getValueAt(bar, 1).toString();
        jId.setText(a);
        jNama.setText(b);
        btnSimpan.setEnabled(false);
        btnHapus.setEnabled(true);
        btnEdit.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPetugasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new petugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel close;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPetugas;
    // End of variables declaration//GEN-END:variables
}
